// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { FeeToken } from "./FeeToken";
import { Transaction } from "./Transaction";

export class ListingPrice {
  static encode(message: ListingPrice, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.timestamp);

    writer.uint32(18);
    writer.string(message.autoListing);

    const feeToken = message.feeToken;
    if (feeToken !== null) {
      writer.uint32(26);
      writer.fork();
      FeeToken.encode(feeToken, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.price);

    const tx = message.tx;
    if (tx !== null) {
      writer.uint32(50);
      writer.fork();
      Transaction.encode(tx, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ListingPrice {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ListingPrice();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.timestamp = reader.uint64();
          break;

        case 2:
          message.autoListing = reader.string();
          break;

        case 3:
          message.feeToken = FeeToken.decode(reader, reader.uint32());
          break;

        case 4:
          message.price = reader.string();
          break;

        case 6:
          message.tx = Transaction.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  timestamp: u64;
  autoListing: string;
  feeToken: FeeToken | null;
  price: string;
  tx: Transaction | null;

  constructor(
    timestamp: u64 = 0,
    autoListing: string = "",
    feeToken: FeeToken | null = null,
    price: string = "",
    tx: Transaction | null = null
  ) {
    this.timestamp = timestamp;
    this.autoListing = autoListing;
    this.feeToken = feeToken;
    this.price = price;
    this.tx = tx;
  }
}
